/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin22_1;

/**
 *
 * @author Clase
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("New User");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        et1 = new javax.swing.JLabel();
        et2 = new javax.swing.JLabel();
        et3 = new javax.swing.JLabel();
        et4 = new javax.swing.JLabel();
        et5 = new javax.swing.JLabel();
        et6 = new javax.swing.JLabel();
        et7 = new javax.swing.JLabel();
        et8 = new javax.swing.JLabel();
        et9 = new javax.swing.JLabel();
        jTextUser = new javax.swing.JTextField();
        jTextFullName = new javax.swing.JTextField();
        jTextUseriID = new javax.swing.JTextField();
        jCBGroup = new javax.swing.JComboBox<>();
        jTextHomeDirectory = new javax.swing.JTextField();
        jCBLogin = new javax.swing.JComboBox<>();
        jPasswordFieldPASS = new javax.swing.JPasswordField();
        jPasswordFieldCONFIRM = new javax.swing.JPasswordField();
        jBcancelar = new javax.swing.JButton();
        jBok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        et1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et1.setForeground(new java.awt.Color(255, 255, 255));
        et1.setText("Create a new user");

        et2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et2.setForeground(new java.awt.Color(255, 255, 255));
        et2.setText("User name :");

        et3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et3.setForeground(new java.awt.Color(255, 255, 255));
        et3.setText("Full name:");

        et4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et4.setForeground(new java.awt.Color(255, 255, 255));
        et4.setText("User ID:");

        et5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et5.setForeground(new java.awt.Color(255, 255, 255));
        et5.setText("Group :");

        et6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et6.setForeground(new java.awt.Color(255, 255, 255));
        et6.setText("Home Directory :");

        et7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et7.setForeground(new java.awt.Color(255, 255, 255));
        et7.setText("Login Shell");

        et8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et8.setForeground(new java.awt.Color(255, 255, 255));
        et8.setText("Password :");

        et9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        et9.setForeground(new java.awt.Color(255, 255, 255));
        et9.setText("Confirm :");

        jTextUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserActionPerformed(evt);
            }
        });

        jTextUseriID.setEditable(false);
        jTextUseriID.setForeground(new java.awt.Color(204, 204, 255));
        jTextUseriID.setText("(automatic)");

        jCBGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "staff", "prueba1", "prueba2" }));
        jCBGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGroupActionPerformed(evt);
            }
        });

        jTextHomeDirectory.setEditable(false);
        jTextHomeDirectory.setForeground(new java.awt.Color(204, 204, 255));
        jTextHomeDirectory.setText("(automatic)");

        jCBLogin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "/bin/ksh", "prueba1", "prueba2" }));

        jBcancelar.setText("Cancel");

        jBok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBok.setText("ok");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(et2)
                            .addComponent(et3)
                            .addComponent(et4)
                            .addComponent(et5)
                            .addComponent(et6)
                            .addComponent(et7)
                            .addComponent(et8)
                            .addComponent(et9))
                        .addGap(53, 53, 53)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextHomeDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(jBcancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBok, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextUser)
                                        .addComponent(jTextFullName)
                                        .addComponent(jTextUseriID, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                        .addComponent(jCBGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPasswordFieldPASS)
                                        .addComponent(jPasswordFieldCONFIRM)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(et1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(et1)
                .addGap(85, 85, 85)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et2)
                    .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et3)
                    .addComponent(jTextFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et4)
                    .addComponent(jTextUseriID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et5)
                    .addComponent(jCBGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et6)
                    .addComponent(jTextHomeDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et7)
                    .addComponent(jCBLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et8)
                    .addComponent(jPasswordFieldPASS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et9)
                    .addComponent(jPasswordFieldCONFIRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserActionPerformed

    private void jCBGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBGroupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel et1;
    private javax.swing.JLabel et2;
    private javax.swing.JLabel et3;
    private javax.swing.JLabel et4;
    private javax.swing.JLabel et5;
    private javax.swing.JLabel et6;
    private javax.swing.JLabel et7;
    private javax.swing.JLabel et8;
    private javax.swing.JLabel et9;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBok;
    private javax.swing.JComboBox<String> jCBGroup;
    private javax.swing.JComboBox<String> jCBLogin;
    private javax.swing.JPasswordField jPasswordFieldCONFIRM;
    private javax.swing.JPasswordField jPasswordFieldPASS;
    private javax.swing.JTextField jTextFullName;
    private javax.swing.JTextField jTextHomeDirectory;
    private javax.swing.JTextField jTextUser;
    private javax.swing.JTextField jTextUseriID;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
